universe = vanilla  
#executable = ./runpy.sh
executable = ./IonAssociation_CONDOR.py

arguments = $(cation) $(anion) $(conc) $(r)

#transfer_input_files = /usr/local/gromacs_gmx/bin/gmx, source, newtopol.py, polymake_v3.py, polymer_formula, oplsaa.ff, IonAssociation_CONDOR.py
transfer_input_files = /usr/local/gromacs_gmx/bin/gmx, source, newtopol.py, polymake_v3.py, polymer_formula, oplsaa.ff, remove_missing_dihedrals.py

+ParallelShutdownPolicy = "WAIT_FOR_ALL"

should_transfer_files = Yes

when_to_transfer_output = on_exit_or_evict

#Requirements = (name == "slot1@sm15") || (name == "slot1@sm16") || (name == "slot1@sm19") || (name == "slot1@sm20") || (name == "slot1@sm21") || \
#               (name == "slot1@sm22") || (name == "slot1@sm23") || (name == "slot1@sm24") || (name == "slot1@sm25") || (name == "slot1@sm26") || \
#               (name == "slot1@sm27") || (name == "slot1@sm28") || (name == "slot1@sm29") || (name == "slot1@sm30") || (name == "slot1@sm34") || \
#               (name == "slot1@sm35")

#Requirements = (name == "slot1@sm51") || (name == "slot1@sm52") || (name == "slot1@sm53") || (name == "slot1@sm54") || (name == "slot1@sm55") || \
#               (name == "slot1@sm56") || (name == "slot1@sm57") || (name == "slot1@sm58") || (name == "slot1@sm59") || (name == "slot1@sm60") || \
#               (name == "slot1@sm61") || (name == "slot1@sm62") || (name == "slot1@sm63") || (name == "slot1@sm64") || (name == "slot1@sm65") || \
#               (name == "slot1@sm66") || (name == "slot1@sm67") || (name == "slot1@sm68") || (name == "slot1@sm69") || (name == "slot1@sm70")

Requirements = (name == "slot1@sm51") || (name == "slot1@sm52") || (name == "slot1@sm53") || (name == "slot1@sm54") || (name == "slot1@sm55") || \
               (name == "slot1@sm56") || (name == "slot1@sm57") || (name == "slot1@sm58") || (name == "slot1@sm59") || (name == "slot1@sm60") || \
               (name == "slot1@sm61") || (name == "slot1@sm62") || (name == "slot1@sm63") || (name == "slot1@sm64") || (name == "slot1@sm65") || \
               (name == "slot1@sm66") || (name == "slot1@sm67") || (name == "slot1@sm68") || (name == "slot1@sm69") || (name == "slot1@sm70") || \
               (name == "slot1@sm71") || (name == "slot1@sm72") || (name == "slot1@sm73") || (name == "slot1@sm74") || (name == "slot1@sm75") || \
               (name == "slot1@sm76") || (name == "slot1@sm77") || (name == "slot1@sm78") || (name == "slot1@sm79") || (name == "slot1@sm80") || \
               (name == "slot1@sm81") || (name == "slot1@sm82") || (name == "slot1@sm83") || (name == "slot1@sm84") || (name == "slot1@sm85") || \
               (name == "slot1@sm86") || (name == "slot1@sm87") || (name == "slot1@sm88") || (name == "slot1@sm89") || (name == "slot1@sm90")

machine_count = 1

output = $(outname).out

error  = $(outname).err

log    = $(outname).log

environment = LD_LIBRARY_PATH=/usr/local/openmpi/lib:/usr/local/gromacs_gmx/lib/

keep_claim_idle = 15

queue
